services:
  giliover-win:
    image: giliover-win
    container_name: giliover-win
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
      - /dev/kvm
      - /dev/dri:/dev/dri
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stop_grace_period: 2m
