services:
  giliover-win:
    image: giliover-win
    container_name: giliover-win
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
      - /dev/kvm
      - /dev/dri:/dev/dri
      - /dev/snd
    cap_add:
      - NET_ADMIN
    stdin_open: true
    privileged: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /dev/snd:/dev/snd
    stop_grace_period: 2m
